### ISSUE TITLE
only the linux version has been getting updated

### ISSUE THREAD

**Issue by bdewilde** [conda-forge/textacy-feedstock#11]
![screen shot 2018-04-25 at 8 22 09 am](https://user-images.githubusercontent.com/2514535/39248709-6ec942e6-4862-11e8-9c56-9bc4638df360.png)

As you can see from the [project page](https://anaconda.org/conda-forge/textacy), the Linux version is current while Windows and Mac versions are stuck at a very old version. How do we update all three? A user recently got bit by this problem: https://github.com/chartbeat-labs/textacy/issues/193

**Comment by rmax** [comment]
Something went wrong in a past rerender and didn't generate the build config files for the other platforms. 

Here is the fix https://github.com/conda-forge/textacy-feedstock/pull/12

**Comment by rmax** [comment]
New packages are up.
