### ISSUE TITLE
this version of textacy is old

### ISSUE THREAD

**Issue by bdewilde** [conda-forge/textacy-feedstock#5]
Hey @rmax , the version of textacy available via conda is 0.3.4, but as of this week, 0.5.0 is available via pip. Would you be able to update the version here? If not, could you give me permissions to do so myself, and I'll figure out how all this conda stuff works to keep it up to date?

**Comment by rmax** [comment]
Hey @bdewilde. Thanks for the reminder. We were stuck at this PR https://github.com/conda-forge/textacy-feedstock/pull/2

I will take over the PR and add you as maintainer.

**Comment by rmax** [comment]
See #6 and #7 for reference. Usually updating a recipe involves:

- Updating the release number and sha256.
- Updating requirements, if needed.
- Updating tests, if needed.
- And, from time to time, run `conda-smithy regenerate`.

As maintainer for this feedstock, you can now merge PRs. Not that PRs must be submitted from forks and not branches within this repository.
